### ISSUE TITLE
Receive an error while running Tx examples

### ISSUE THREAD

**Issue by MrsFlower** [deepwavedigital/airstack-examples#2]
I run airstack_tx_demo.grc and transmit_tone.py in AIR-T. Then I got the same mistake.

[ERROR] SoapySSDPEndpoint::sendTo(udp://[ff02::c]:1900) = -1
  sendto(udp://[ff02::c]:1900) [99: Cannot assign requested address]
Traceback (most recent call last):
  File "/home/demo/download/airstack-examples-master/python/transmit_tone.py", line 98, in <module>
    transmit_tone(pars.freq, pars.chan, pars.fs, pars.gain, pars.buff_len)
  File "/home/demo/download/airstack-examples-master/python/transmit_tone.py", line 47, in transmit_tone
    sdr.setSampleRate(SOAPY_SDR_TX, chan, fs)  # Set sample rate
  File "/usr/lib/python3/dist-packages/SoapySDR.py", line 1531, in setSampleRate
    return _SoapySDR.Device_setSampleRate(self, direction, channel, rate)
RuntimeError: Invalid parameter passed to SoapyAIRT::setSampleRate()!  Details: decimation factor = 4

In your doc I have seen that SoapySSDPEndpoint error is not a big deal. But Tx example just can`t work and I don`t konw why.
Rx examples seem to run normally.
Thanks a lot.

**Comment by dwd-pete** [comment]
The TX examples will not work with older versions of AirStack. Your version of AirStack does not have interpolation filters for TX, so it cannot set the sample rate.

Upgrading your version of AirStack will solve the issue.
